#!/usr/bin/env php
<?php

declare(strict_types=1);

include $_composer_autoload_path ?? __DIR__ . '/vendor/autoload.php';

$testFile = null;
$objectFile = null;
$disasm = false;

$binName = array_shift($argv);
foreach ($argv as $v) {
    if ($v === '--disasm') {
        $disasm = true;
        continue;
    }

    if (!$testFile) {
        $testFile = $v;
        continue;
    }

    if (!$objectFile) {
        $objectFile = $v;
        continue;
    }

    echo "Unexpected command argument $v";
    exit;
}

$test = require $testFile;

if ($objectFile) {
    $test->setObjectFile($objectFile);
}
$test->parseObject();

if ($disasm) {
    $test->enableDisasm();
}

$reflectionClass = new ReflectionClass($test);

// TODO: Setup and teardown.

foreach ($reflectionClass->getMethods() as $reflectionMethod) {
    if ($reflectionMethod->isPublic() && str_starts_with($reflectionMethod->name, 'test')) {
        echo $reflectionMethod->name . "...\n";
        call_user_func([$test, $reflectionMethod->name]);
    }
}

