#!/usr/bin/env php
<?php declare(strict_types=1);

require $_composer_autoload_path ?? __DIR__ . '/vendor/autoload.php';

use Lhsazevedo\Sh4ObjTest\Console\TestCommand;

$app = new Symfony\Component\Console\Application();
$command = new TestCommand();

$app->add($command);

$app->setDefaultCommand($command->getName(), isSingleCommand: true);

$app->run();
